### PR TITLE
Create Exercise 5

### PR DESCRIPTION
**Pull request by jrh5221**
This stumped me for a while, but it turned out to be incredibly easy when I looked at it from a different perspective.  The first three exercises don't take much, but I feel this one would be a good addition to your examples.  Feel free to adjust if you see a way to make it more readable.

### CODE REVIEW

**Review by arminherling — CHANGES_REQUESTED** [review]
Please add the exercise text in a comment at the top of the file, just like in the other files

**Comment by arminherling** [comment]
Oh wow I did not expect anyone to create pull requests for this repo, since this was just for me to keep track of which excercises I finished :smiley: 
I'll happily merge the pull request if you add the exercise text in a comment at the top of the file :+1:

**Comment by jrh5221** [comment]
I appreciate you having this repo available.  It has literally been the closest thing to a complete collection of these exercises I have been able to find.  I have updated the exercise on my third commit, should be good to go.

**Review by arminherling — APPROVED** [review]

**Comment by arminherling** [comment]
Looks good, this repo doesnt contain all exercises since i skipped some for various reasons.
Feel free to create more pull requests, i'll gladly merge them 👍

**Pull request merged**
